/////////////////////////////////fire.c/////////////////////////////////
//
//Generated by Parted by Martin Coumont (redphoenix)
//
//LiteC Script file from 24.12.2015 ; 08:41:05:
//
//////////////////////////////////////////////////////////////////////////////
#define PRAGMA_PRINT "[Fire] "

VECTOR* parted_temp_vec = { x=0;y=0;z=0; }
VECTOR* parted_temp2_vec = { x=0;y=0;z=0; }
ANGLE* parted_temp_ang = { pan=0;tilt=0;roll=0; }
BMAP* fire3_map = NULL;
BMAP* fire1_map = NULL;
BMAP* smoke1_map = NULL;

/////////////////////////////////particle code/////////////////////////////////

void firstex_base_event(PARTICLE* p) {

    p.size += 0.000* time_step;
    p.alpha = clamp(p.alpha-7.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)5.000)%100;
}

void firstex_base(PARTICLE* p) {
   p.size = 5.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(6.000)+(-3.000);
   p.vel_y = random(6.000)+(-3.000);
   p.vel_z = random(6.000)+(-3.000);
   vec_normalize(p.vel_x,5.195);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = firstex_base_event;
}

void sparks_base(PARTICLE* p) {
   p.size = 1.000;
   p.alpha = 100.000;
   p.red = 255;
   p.green = 128;
   p.blue = 64;
   p.skill_c = 0.5;
   p.vel_x = random(6.000)+(-3.000);
   p.vel_y = random(6.000)+(-3.000);
   p.vel_z = random(6.000)+(-3.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = NULL;
}

void secondex_base_event(PARTICLE* p) {
      p.size += 1.000* time_step;
      p.alpha = clamp(p.alpha-4.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)5.000)%100;
}

void secondex_base(PARTICLE* p) {
   p.size = 10.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = secondex_base_event;
}

void thirdex_base_event(PARTICLE* p) {
      p.size += 2.000* time_step;
      p.alpha = clamp(p.alpha-3.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)7.500)%100;
}

void thirdex_base(PARTICLE* p) {
   p.size = 15.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = thirdex_base_event;
}

void fourthex_base_event(PARTICLE* p) {
      p.size += 3.000* time_step;
      p.alpha = clamp(p.alpha-3.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)10.000)%100;
}

void fourthex_base(PARTICLE* p) {
   p.size = 20.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = fourthex_base_event;
}

void fifthex_base_event(PARTICLE* p) {
      p.size += 4.000* time_step;
      p.alpha = clamp(p.alpha-3.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)15.000)%100;
}

void fifthex_base(PARTICLE* p) {
   p.size = 25.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = fifthex_base_event;
}

void sixthex_base_event(PARTICLE* p) {
      p.size += 5.000* time_step;
      p.alpha = clamp(p.alpha-3.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)15.000)%100;
}

void sixthex_base(PARTICLE* p) {
   p.size = 25.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire3_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = sixthex_base_event;
}

void seventhex_base_event(PARTICLE* p) {
      p.size += 6.000* time_step;
      p.alpha = clamp(p.alpha-5.000* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)20.000)%100;
}

void seventhex_base(PARTICLE* p) {
   p.size = 30.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(10.000)+(-5.000);
   p.vel_y = random(10.000)+(-5.000);
   p.vel_z = random(10.000)+(-5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = fire1_map;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = seventhex_base_event;
}

void smoke_base_event(PARTICLE* p) {
      p.size += 1.000* time_step;
      p.alpha = clamp(p.alpha-0.010* time_step,-1,100);
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
}

void smoke_base(PARTICLE* p) {
   p.size = 4.000;
   p.alpha = 19.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(6.000)+(-3.000);
   p.vel_y = random(6.000)+(-3.000);
   p.vel_z = random(6.000)+(-3.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.bmap = smoke1_map;
   p.flags = TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = smoke_base_event;
}

/////////////////////////////////emitter actions/////////////////////////////////

action firstex_emitter() {
   var eff_frac; eff_frac = 0;
wait(1);
   while(my) {
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(firstex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
      if(!(total_frames % 2)) {
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(sparks_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(secondex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(thirdex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(fourthex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(fifthex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(sixthex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(seventhex_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(smoke_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      wait(1);
   }
}
/////////////////////////////////creation/////////////////////////////////

void fire_create( VECTOR *position )
{
   if( !position )
    position = vector(0, 0, 0);

   fire3_map     = bmap_create(game_asset_get_2d_fx("fire3.tga"));
   fire1_map     = bmap_create(game_asset_get_2d_fx("fire1.tga"));
   smoke1_map    = bmap_create(game_asset_get_2d_fx("smoke1.tga"));

   you = ent_create(NULL,position,firstex_emitter);
   wait(3.0);

   if(you)
   {
      vec_add(you.x,vector(-85.010,-6.914,21.610));
      vec_set(you.pan,vector(0.000,0.000,0.000));
      vec_set(you.scale_x,vector(1.000,1.000,1.000));
      set(you,PASSABLE);
      set(you,INVISIBLE);
   }
}
