/////////////////////////////////smoke.c/////////////////////////////////
//
//Generated by Parted by Martin Coumont (redphoenix)
//
//LiteC Script file from 24.12.2015 ; 08:48:33:
//
//////////////////////////////////////////////////////////////////////////////
#define PRAGMA_PRINT "[Smoke] "

 VECTOR* parted_temp_vec = { x=0;y=0;z=0; }
 VECTOR* parted_temp2_vec = { x=0;y=0;z=0; }
 ANGLE* parted_temp_ang = { pan=0;tilt=0;roll=0; }

/////////////////////////////////particle code/////////////////////////////////

void New_Base_Effect_Child_child_event(PARTICLE* p) {
if (p.lifespan > 30.000) {
      p.skill_a |= 1;
       p.alpha = clamp(p.alpha+0.500* time_step,-1,100);
   }
      p.size += 2.000* time_step;
   if(p.lifespan <= 30.000 || (p.skill_a & 4)) {
      p.skill_a |= 4;
       p.alpha = clamp(p.alpha-0.500* time_step,-1,100);
   }
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
}

void New_Base_Effect_Child_child(PARTICLE* p) {
   p.size = 21.000;
   p.alpha = 0.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(1.000)+(-0.500);
   p.vel_y = random(1.000)+(-0.500);
   p.vel_z = random(2.637)+(0.363);
   p.lifespan = 60.000;
   p.gravity = 0.000;
   p.flags = TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = New_Base_Effect_Child_child_event;
}

void Base_Effect1_base_event(PARTICLE* p) {
   if(p.lifespan <= 20.000) {
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,p.x);
      if(!(total_frames % 50)) {
         p.skill_c += 1.000*time_step*6.25;
         if(p.skill_c >= 1){
            effect(New_Base_Effect_Child_child,integer(p.skill_c),parted_temp_vec,nullvector);
            p.skill_c -= integer(p.skill_c);
         }
      }
   }
}

void Base_Effect1_base(PARTICLE* p) {
   p.size = 4.000;
   p.alpha = 0.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(8.000)+(-4.000);
   p.vel_y = random(8.000)+(-4.000);
   p.vel_z = (5.000);
   p.lifespan = 40.000;
   p.gravity = 0.000;
   p.flags = BRIGHT | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = Base_Effect1_base_event;
}

/////////////////////////////////emitter actions/////////////////////////////////

action Base_Effect1_emitter() {
   var eff_frac; eff_frac = 0;
wait(1);
   while(my) {
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 1.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(Base_Effect1_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      wait(1);
   }
}
/////////////////////////////////creation/////////////////////////////////

void smoke_create(VECTOR* position)
{
   if(!position)
    position = vector(0, 0, 0);
   wait(3);
   you = ent_create(NULL,position,Base_Effect1_emitter);
   if(you) {
      vec_add(you.x,vector(37.228,-91.124,3.461));
      vec_set(you.pan,vector(0.000,0.000,0.000));
      vec_set(you.scale_x,vector(1.000,1.000,1.000));
      set(you,PASSABLE);
      set(you,INVISIBLE);
   }
}
