/////////////////////////////////sparkle.c/////////////////////////////////
//
//Generated by Parted by Martin Coumont (redphoenix)
//
//LiteC Script file from 24.12.2015 ; 08:50:13:
//
//////////////////////////////////////////////////////////////////////////////

/////////////////////////////////header/////////////////////////////////
#define PRAGMA_PRINT "[Sparkle] "

VECTOR* parted_temp_vec = { x=0;y=0;z=0; }
VECTOR* parted_temp2_vec = { x=0;y=0;z=0; }
ANGLE* parted_temp_ang = { pan=0;tilt=0;roll=0; }

/////////////////////////////////particle code/////////////////////////////////

void Base_Effect_base_event(PARTICLE* p) {
   if(p.lifespan <= 13.000 || (p.skill_a & 1)) {
      p.skill_a |= 1;
       p.alpha = clamp(p.alpha-8.000* time_step,-1,100);
   }
      p.size -= 1.000* time_step;
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)3.000)%100;
}

void Base_Effect_base(PARTICLE* p) {
   p.size = 29.000;
   p.alpha = 100.000;
   p.red = 128;
   p.green = 128;
   p.blue = 128;
   p.skill_c = 0.5;
   p.vel_x = random(12.000)+(-6.000);
   p.vel_y = random(12.000)+(-6.000);
   p.vel_z = random(12.000)+(-6.000);
   vec_normalize(p.vel_x,10.392);
   p.lifespan = 35.000;
   p.gravity = 0.000;
   p.flags = BRIGHT | BEAM | STREAK | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = Base_Effect_base_event;
}

void Base_Effect1_base_event(PARTICLE* p) {
   if(p.lifespan <= 13.000 || (p.skill_a & 1)) {
      p.skill_a |= 1;
       p.alpha = clamp(p.alpha-8.000* time_step,-1,100);
   }
      p.size -= 1.000* time_step;
   if(p.alpha < 0 || p.size < 0) p.lifespan = 0;
   p.vel_x = p.skill_x*p.skill_d/50;
   p.vel_y = p.skill_y*p.skill_d/50;
   p.vel_z = p.skill_z*p.skill_d/50;
   p.skill_d = (p.skill_d + time_step*(var)3.000)%100;
}

void Base_Effect1_base(PARTICLE* p) {
   p.size = 29.000;
   p.alpha = 100.000;
   p.red = 228;
   p.green = 62;
   p.blue = 20;
   p.skill_c = 0.5;
   p.vel_x = random(12.000)+(-6.000);
   p.vel_y = random(12.000)+(-6.000);
   p.vel_z = random(12.000)+(-6.000);
   vec_normalize(p.vel_x,10.392);
   p.lifespan = 35.000;
   p.gravity = 0.000;
   p.flags = BRIGHT | BEAM | STREAK | TRANSLUCENT | MOVE;
   p.skill_x = p.vel_x;
   p.skill_y = p.vel_y;
   p.skill_z = p.vel_z;
   p.event = Base_Effect1_base_event;
}

/////////////////////////////////emitter actions/////////////////////////////////

action Base_Effect_emitter() {
   var eff_frac; eff_frac = 0;
wait(1);
   while(my) {
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 5.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(Base_Effect_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      parted_temp_vec.x = 0.000;
      parted_temp_vec.y = 0.000;
      parted_temp_vec.z = 0.000;
      vec_add(parted_temp_vec,my.x);
         eff_frac += 3.000*time_step*6.25;
         if(eff_frac >= 1){
            effect(Base_Effect1_base,integer(eff_frac),parted_temp_vec,nullvector);
             eff_frac -= integer(eff_frac);
         }
      wait(1);
   }
}
/////////////////////////////////creation/////////////////////////////////

void sparkle_create(VECTOR* position) {
   if(!position)
    position = nullvector;
   wait(3);
   you = ent_create(NULL,position,Base_Effect_emitter);
   if(you) {
      vec_add(you.x,vector(-12.178,-85.878,51.929));
      vec_set(you.pan,vector(0.000,0.000,0.000));
      vec_set(you.scale_x,vector(1.000,1.000,1.000));
      set(you,PASSABLE);
      set(you,INVISIBLE);
   }
}
