set "REPOPATH=H:\Development\DPFL"
set "GAMEPATH=.\"
set "ACKPATH=H:\Development\Gamestudio\GStudio8\"
set "RARPATH=C:\Program Files\WinRAR\"
set "DROPBOXPATH=D:\Dropbox"
set "DROPBOXCLIENT=C:\Program Files (x86)\Dropbox\Client"
set "CLOC=cloc"
